feat: add LevelDistribution Endpoint
42Gyeongsan-side-project/server pull request #19
Opened 2024-06-12 05:32 UTC by joejaeyoung

## 이 PR의 기능은 무엇인가요?

Web Main Page -1 에 있는 여행 중인 유저 레벨 분포 관련 기능입니다.
endpoint는 /levels이며, map 형식으로 받을 수 있습니다.

전체 유저 관련 데이터를 DB에서 받아온 후 정렬을 거쳐, Map에 데이터를 넣는 식으로 진행했는데, 나중에 더 효율적인 방법으로 리팩토링하면 좋을 것 같습니다.

## 제출하기 전에
- [ ] 이 PR은 오타를 수정하거나 문서를 개선합니다(이 경우 다른 확인은 무시해도 됩니다).
- [X] [기여자 가이드라인](https://github.com/42Gyeongsan-side-project/reference/blob/main/CONTRIBUTING.md#create-a-pull-request)을 읽으셨나요?
      풀 리퀘스트 섹션을 읽었나요?
- [ ] Github 이슈 또는 [포럼]()을 통해 논의 또는 승인되었나요? 그렇다면 링크를 추가하세요. 
- [X] 변경 사항으로 문서를 업데이트하셨나요? 여기 [문서 가이드라인](https://github.com/42Gyeongsan-side-project/reference/blob/main/CONTRIBUTING.md) 및 [주석에 대한 팁](https://github.com/42Gyeongsan-side-project/reference/blob/main/CONTRIBUTING.md)을 참조하세요.
- [ ] 필요한 테스트를 새로 작성했나요?

2024-06-12 08:40 UTC, joonwan commented
변경된 코드를 보았을때 엄청난 노력의 흔적이 보였습니다 정말 고생하셨습니다.!!

2024-06-12 08:41 UTC, joonwan approved these changes
very good!!!

2024-06-12 16:17 UTC, wonhyeongseo requested changes
우선 유저 레벨 분포 기능을 구현한 것에 대해 축하드립니다! 코드를 살펴보니 전반적으로 잘 작성되었고, 향후 개선 사항도 인지하고 계신 것 같아 좋습니다.

몇 가지 작은 스타일 개선 사항을 제안하겠습니다. 먼저, 일관성 있는 코딩 스타일을 유지하는 것이 중요합니다. 예를 들어, 공백과 따옴표 사용에 대한 규칙을 정하고 일관되게 적용하면 코드 가독성이 높아질 것입니다.

또한, `java.util` 패키지에서 필요한 클래스만 import하는 것이 좋습니다. 전체 패키지를 import하면 코드에서 사용하지 않는 클래스까지 포함되어 불필요한 메모리 낭비가 발생할 수 있습니다.

전반적으로 좋은 작업이었습니다. 계속 이렇게 노력하신다면 더욱 훌륭한 개발자가 되실 것이라 믿습니다. 앞으로도 화이팅하세요!

2024-06-12 16:17 UTC, wonhyeongseo commented on src/main/java/ggs/srr/service/initdata/InitDataService.java
> +        return new FtUser(level,resourceOwnerId, email, intraId, imgUri,correction_point, wallet);
```suggestion
        return new FtUser(level, resourceOwnerId, email, intraId, imgUri,correction_point, wallet);
```

2024-06-12 16:17 UTC, wonhyeongseo commented on src/main/java/ggs/srr/domain/FtUser.java
> +                '}';
```suggestion
        return String.format("FtUser{level=%f, intraId='%s'}", level, intraId);
```
이렇게 포맷 스트링을 사용해보면 어떨까요? 아니면 적어도 마지막에 `'\''` 나 `'}'` 가 쌍따옴표로 통일되면 좋겠어요!

2024-06-12 16:17 UTC, wonhyeongseo commented on src/main/java/ggs/srr/service/initdata/InitDataService.java
> +        System.out.println(usersData);
```suggestion
        List<LinkedHashMap<String, Object>> usersData = (List<LinkedHashMap<String, Object>>)cursusUsers;
```
디버깅 구문이 들어온 것 같아요! 확인 부탁드립니다.

2024-06-12 16:17 UTC, wonhyeongseo commented on src/main/java/ggs/srr/service/user/FtUserService.java
> +import java.util.*;
```suggestion
import java.util.*;
```

util에서 필요한 부분들만 임포트 부탁드립니다 :)

2024-06-13 00:06 UTC, joejaeyoung commented on src/main/java/ggs/srr/service/initdata/InitDataService.java
> +        return new FtUser(level,resourceOwnerId, email, intraId, imgUri,correction_point, wallet);
이부분은 상상도 못했습니다.. 꼼꼼한 리뷰 감사합니다.

2024-06-13 00:10 UTC, joejaeyoung commented on src/main/java/ggs/srr/service/user/FtUserService.java
> +import java.util.*;
이부분은 
`import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Comparator;
import java.util.ArrayList;`
intellij 에서 일정 수 이상의 util import 시에 *로 초기화시켜서, 다시 수정완료했습니다.

2024-06-13 00:15 UTC, joejaeyoung commented on src/main/java/ggs/srr/service/user/FtUserService.java
> +import java.util.*;
이 부분은 평가 포인트 랭킹 시에 수정해서 push해도 괜찮을까요?

2024-06-13 00:17 UTC, joejaeyoung commented on src/main/java/ggs/srr/domain/FtUser.java
> +                '}';
java에서 자동으로 만들어주는 toString인 것 같은데, string 이면 "", charcter면 '' 차이로 발생한 것 같습니다!
@joonwan 같이 확인 부탁드려요

2024-06-13 02:30 UTC, joejaeyoung commented on src/main/java/ggs/srr/service/user/FtUserService.java
> +import java.util.*;
```suggestion
import java.util.*;
import java.util.Collections; import java.util.HashMap; import java.util.List; import java.util.Map; import java.util.Comparator; import java.util.ArrayList;
```

2024-06-13 02:59 UTC, joonwan commented on src/main/java/ggs/srr/domain/FtUser.java
> +                '}';
데이터 확인용으로 출력하기위헤 toString을 ide를 이용해 오버라이딩 해버렸는데 깔끔하지 못하게한 점 죄송합니다. 

@wonhyeongseo 원형님이 말씀하신 것 처럼 포멧을 정해 로그를 출력하는 방향이 좋다고 생각합니다!!

2024-06-13 07:20 UTC, merged